import NavbarPage from "@/components/navbar/Navbar";
import Footer from "@/components/ui/Footer";
import AntProvider from "@/lib/AntdRegistry";
import ReduxProviders from "@/lib/Provider";
import Providers from "@/lib/Provider";
import type { Metadata } from "next";


import "./globals.css";




export const metadata: Metadata = {
  title: "Softmax Online School",
  description: "Generated by Rahul Noob Dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <ReduxProviders>
        <Providers>
        <AntProvider>
        <NavbarPage></NavbarPage>
        {children}
        <Footer/>
        </AntProvider>
        </Providers>
        </ReduxProviders>
        </body>
    </html>
  );
}
